name: Python Unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unittests
        run: python -m unittest test.test_unittest -v

      - name: Notify on success
        if: success()
        run: echo "Unit tests passed successfully."

      - name: Notify on failure
        if: failure()
        run: echo "Unit tests failed."

